### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by jkukko** [Veikkosuhonen/ot-harjoitustyo#1]
Ladattu: 28.4.2020 klo. 19.15

Todella mielenkiintoinen projekti. Vaikka ymmärtääkseni käyttöliittymä ei ole pääpainolla tässä kurssilla, se oli ohjelmassa tosi hyvä!

En jostain syystä saanut mp3 äänitiedostoa toimimaan (voi kylläkin johtua käyttäjästä). Lisäsin m3-filen, mutta kun klikkasin sitä ohjelmassa, tuli virheilmoitus, että “could  not create player”. Yrittäessä painaa playtä, niin tulee toinen virheilmoitus (voi johtua koska aikaisemmassa vaiheessa tuli virhe).

**Koodin Laatu**

- Yleisesti koodin laatu hyvätasoista ja helposti luettavaa. Joskin siellä täällä jotain poikkeavuutta. Esim. välillä koodirivien välissä tyhjä rivi ja taas toisaalla ei ole. Kuitenkin pääsäntöisesti hyvää koodia.

- Mieting että voisiko noita luokkia nimetä eri tavalla: Setting, Settings, SettingService. Tutkiessani projektiasia piti pitää arkkitehtuurikuvaus vieressä, niin ymmärsin täysin rakenteen. Voi olla että nykyinen on paras ratkaisu, mutta silloin voisi tarkemmin avata sitä arkkitehtuuridokumentissa.

- FileSettingDao muutama metodi / konstruktori ovat aika pitkiä. Näitä voisi miettiä, jos voisi paloitella pienempiin osakokonaisuuksiiin.

- Välillä koodissa voisi olla kommentointia. Ne helpottaisivat lukijaa ymmärtämään, mitä missäkin tehdään.

- Ajoin testikattavuusraportin ja huomasin, että domainissa ja dao -osuuksissa oli hyvä testikattavuus. Varmaankin tuohon media kannattaa lisätä jotain testejä.

Mun mielestä tosi mielenkiintoinen projekti. Hyvää duunia ja nyt loppukiri vaan!

**Comment by Veikkosuhonen** [comment]
Kiitos paljon palautteesta, pidän kommenttisi mielessä jatkokehittelyssä. Saamasi virheilmoitus on kummallinen kun nykytilassaan (viikon 6 release) sovelluksen ei sellaista pitäisi antaa... joka tapauksessa vika on todennäköisimmin täällä kehittäjän päässä. Jos haluat vielä kokeilla, lataa repo koneellesi ja aja projektihakemistossa `mvn compile exec:java -Dexec.mainClass=pakkaus.Paaohjelma`. Uusimman releasenkin _pitäisi_ kyllä toimia normaalisti. Ja vielä kerran kiitos siitä että jaksoit vaivata päätäsi spagettikoodillani ja kehnolla dokumentaatiolla.
